### ISSUE TITLE
tsn-model.h

### ISSUE THREAD

**Issue by berrlyy** [DenKrysos/Time-Aware-Shaper-TAS-in-ns-3#1]
hello where can I find tsn-model.h ?

**Comment by DenKrysos** [comment]
I'm not sure what you mean. There is no such thing with our code.

**Comment by berrlyy** [comment]
> I'm not sure what you mean. There is no such thing with our code.

Sorry, it is tsn-module.h. In the step "./waf", there have some wrong. ns/tsn-module.h is  in the examples->tsn-examples1.cc=>"# include ns/tsn-model.h". In my ns folder,there is no such file. Thanks for answering my questions！
